namespace D3lg4doMaps.Places.Public.Models.Details.Reviews;

/// <summary>
/// Represents a collection of reviews for a place.
/// </summary>
/// <remarks>
/// Includes individual reviews as well as an optional summary generated by AI.
/// </remarks>
public sealed class PlaceReviews {
    /// <summary>
    /// Gets the unique identifier of the place.
    /// </summary>
    public string PlaceId { get; internal set; } = null!;

    /// <summary>
    /// Gets the name of the place.
    /// </summary>
    public string DisplayName { get; internal set; } = null!;

    /// <summary>
    /// Gets the list of user reviews.
    /// </summary>
    public IReadOnlyList<Review> Reviews { get; internal set; } = [];

    /// <summary>
    /// Gets a summary of the reviews generated by Gemini, if available.
    /// </summary>
    public ReviewSummary? ReviewSummary { get; internal set; }

    /// <summary>
    /// Gets the URI to view reviews in Google Maps.
    /// </summary>
    public string? ReviewsUri { get; internal set; }
}